---
id: 0xA1
name: commander

threads:
  commandThread:
    firstTime: 1400_ms
    period: 1_s
    priority: 800

subscribe:
  corfu::uplinkTelecommandTopic:
    fifo: 12

publish: corfu::appIsAliveTopic
  corfu::telecommandTopic
  timedTelecommandTopic

anomalies:
  - OneDayNoCommand
  - NoValidSignatures

telecommands:
  NOP:
    id: 1

standard_telemetry:
  cmdCounter: uint16_t
  lastCmdIndex: uint16_t
  lastCmdInSeqCounter: uint16_t
  authErrorCounter: uint16_t
  lastCmdReceivedAt: int64_t # uint32_t should be enough here?
  iteration: uint16_t
  # crcErrorCounter: int16_t => UPLINK
