---
id: 0xA7
name: downlink-manager
threads:
  dlmThread:
    firstTime: 1300_ms
    period: 1_s
    priority: 400

subscribe:
  corfu::standardTelemetryTopic:
    fifo: 12
  corfu::extendedTelemetryTopic:
    fifo: 12
  historicTelemetryTopic:
    fifo: 12

publish:
  - corfu::appIsAliveTopic
  - corfu::anomalyTopic
  - corfu::downlinkTelemetryTopic # debug-topic

anomalies:
  - SendQueuesFull

configurable_parameters:
  MaxNumStdTM:
    type: uint8_t
    default_value: 6
  MaxNumExtTm:
    type: uint8_t
    default_value: 6

telecommands:
  NOP:
    id: 1
  PauseStandardTM:
    id: 2
  ResumeStandardTM:
    id: 3
  FlushSTDQueue:
    id: 4
  FlushEXTQueue:
    id: 5
  ResetRadio:
    id: 6
  SetMaxNumStdTM:
    id: 7
    fields:
      value: uint8_t
  SetMaxNumExtTM:
    id: 8
    fields:
      value: uint8_t

standard_telemetry:
  stdTMQueue: uint8_t
  extTMQueue: uint8_t

  # what about transceiver status?
