---
id: 0xAE # or 0xB2
name: time-and-mode-manager
threads:
  tammThread:
    firstTime: 1200_ms
    period: 1_s
    priority: 400

subscribe:
  criticalAnomalyTopic: direct # causes switching to safe mode

publish:
  - corfu::anomalyTopic
  - corfu::appIsAliveTopic
  - timeAndModeTopic

telecommands:
  NOP:
    id: 1
  EnterSafeMode:
    id: 2
  EnterNominal:
    id: 4
  SetUTC:
    id: 8
    fields:
      nanoSeconds: int64_t
  AdjustUTC:
    id: 9
    fields:
      deltaTime: int64_t
  SetClockDrift:
    id: 10
    fields:
      driftInNsPerS: int32_t
  NextStartInLEOP:
    id: 240

standard_telemetry:
  mode: uint8_t
  lastModeChange: int64_t
  utc: int64_t
  uptime: int64_t
  drift: double
