---
id: 0x83
# file-system
configurable_parameters:
  max_file_size_in_bytes:
    type: uint32_t
    default_value: 512000
publish:
  - corfu::extendedTelemetryTopic
# anomalies:
#  - FlashErrorOnWrite
telecommands:
  NOP:
    id: 1
  SendBBBM:
    id: 2
  SendFileInfo: # @todo: IN DATA UPLOAD EINBAUEN
    id: 3
    fields:
      numIDs: uint16_t
      fileIDs:
        array:
          length: 4
          type: uint16_t
  sendFileList:
    id: 4
  WriteToMRAM:
    id: 5
  ReadFromMRAM:
    id: 6
structs:
  fileInfo:
    fileID: uint8_t
    pageID: uint32_t
    pageOffset: uint32_t
    fileSize: uint32_t
standard_telemetry:
  badBlocks: uint16_t
  freeBlocks: uint16_t
extended_telemetry:
  BadBlockMarkers:
    id: 2
    fields:
      bitmap:
        bit_array:
          length: 1024 # 128Bytes
  FileDetails:
    id: 3
    fields:
      entry:
        array:
          length: 4
          type: fileInfo
    FileList:
      id: 4
      fields:
        array:
          length: 100
          type: uint8_t
