---
id: 0xA0
# radio for up- and downlink
threads:
  txThread:
    firstTime: 1200_ms
    period: 1_s
    priority: 790
# app parameters
configurable_parameters:
  DOWNLINK_PORT:
    type: uint16_t
    default_value: 8669
  UPLINK_PORT:
    type: uint16_t
    default_value: 8670
# topics
subscribe:
  corfu::downlinkTelemetryTopic:
    fifo: 12
  radioUpTopic: direct
  radioUploadTopic: direct
publish:
  - corfu::anomalyTopic
  - corfu::appIsAliveTopic
  - corfu::uplinkTelecommandTopic
  - radioDownTopic
  - fileTransferTopic
anomalies:
  - RadioTXError
  - RadioRXError
# commands
telecommands:
  NOP:
    id: 1
  ResetReceiver:
    id: 2
    fields:
      receiverID: uint8_t
  StartDownlink:
    id: 3
  StopDownlink:
    id: 4
  ResetModem:
    id: 5
  SetTransmissionPower:
    id: 6
    fields:
      trPow: uint16_t
# telemetry
standard_telemetry:
  isDownlinkActive: bool
  transmissionPower: uint16_t
  isUplinkActive: bool
  tcUplinkCtr: uint16_t
