# config for corfu-generated application
---
id: 0x80
name: boot-manager
#
telecommands:
  NOP:
    id: 1
  Reboot:
    id: 2
  SetPermantentAddressForNextBoot:
    id: 3
    fields:
      ImageAddress: uint32_t
  SetTemporaryAddressForNextBoot:
    id: 4
    fields:
      ImageAddress: uint32_t

standard_telemetry:
  bootCounter: uint8_t
  ImageAddress: uint32_t
